In [1]:
import numpy as np
from keras.utils import np_utils
import tensorflow as tf

Using TensorFlow backend.


In [2]:
# Using TensorFlow 1.0.0; use tf.python_io in later versions
tf.python_io = tf

In [3]:
# Set random seed
np.random.seed(42)

# Our data
X = np.array([[0,0],[0,1],[1,0],[1,1]]).astype('float32')
X

array([[ 0.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  1.]], dtype=float32)

In [4]:
y = np.array([[0],[1],[1],[0]]).astype('float32')
y

array([[ 0.],
       [ 1.],
       [ 1.],
       [ 0.]], dtype=float32)

In [5]:
y = np_utils.to_categorical(y)
y

array([[ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.]])

In [6]:
# Initial Setup for Keras
from keras.models import Sequential
from keras.layers.core import Dense, Activation

In [7]:
# Building the model
xor = Sequential()

In [8]:
# Add required layers
xor.add(Dense(4, input_dim=2))

In [9]:
xor.add(Activation("sigmoid"))

In [10]:
xor.add(Dense(2))

In [11]:
xor.add(Activation("sigmoid"))

In [12]:
xor.compile(loss="categorical_crossentropy", \
            optimizer="adam", metrics = ['accuracy'])

In [13]:
# Uncomment this line to print the model architecture
xor.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 4)                 12        
_________________________________________________________________
activation_1 (Activation)    (None, 4)                 0         
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 10        
_________________________________________________________________
activation_2 (Activation)    (None, 2)                 0         
Total params: 22
Trainable params: 22
Non-trainable params: 0
_________________________________________________________________


In [14]:
# Fitting the model
history = xor.fit(X, y, epochs=1000, verbose=0)

In [15]:
# Scoring the model
score = xor.evaluate(X, y)
print("\nAccuracy: ", score[-1])

# Checking the predictions
print("\nPredictions:")
print(xor.predict_proba(X))

4/4 [==============================] - 0s 6ms/step

Accuracy:  1.0

Predictions:
[[ 0.24048695  0.05572684]
 [ 0.07508446  0.13587168]
 [ 0.07566866  0.16838533]
 [ 0.11505008  0.09492444]]
